import time
import calendar
print("Full time with GMT Below")
localtime= time.localtime(time.time())
print(localtime)
print('\n\n')
print('Short local time')
print(time.asctime(time.localtime(time.time())))
print('\n\n')
print('particular Month of the Year')
print(calendar.month(2018,1))
print('\n\n')
print("checking Year 1998 is a leap year or Not")
print(calendar.isleap(1998))
print('\n\n')
print("printing first Day of the Week ")
print(calendar.firstweekday())
print('\n\n')
print('finding leap days from year 2000-2001')
print(calendar.leapdays(2000,2001))
print('\n\n')
print("index of days in a month")
print(calendar.monthcalendar(2019,1))
print('\n\n')
